name: Go tests and deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  test-and-lint:  # Первый job для всех проверок
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'
        cache: false  # Отключаем кэширование Go модулей

    - name: Install SQLite (if not present)
      run: sudo apt-get update && sudo apt-get install -y sqlite3

    - name: Build
      run: go build -v ./...

    - name: Tests
      run: go test -v ./...

    - name: Test-race
      run: go test -race -v ./...

    - uses: golangci/golangci-lint-action@v3
      with:
        skip-cache: true  # Отключаем кэширование для линтера
        skip-pkg-cache: true
        skip-build-cache: true
        args: --timeout=5m

    - name: Vet
      run: go vet ./...

  deploy: # Второй job для деплоя

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test-and-lint
    if: startsWith(github.ref, 'refs/tags')

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: vgdryukov/sprint11-itog

    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

